networks:
  proxy:
    external: true

services:
  demo_hello:
    image: demo_hello:latest
    container_name: demo_hello
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 9004:80
    networks:
      - proxy

# -- add following lines in Caddyfile:
# app-demo-hello.robertthecoder.org {
#   reverse_proxy demo_hello:80
# }
